[default]

[testing]
    APP_NAME = "meios de pagamento"
    DATABASE_URL = "sqlite://:memory:"
    TRANSFER_AUTHORIZATION_URL = "https://util.devi.tools/api/v2/authorize"
    TRANSFER_NOTIFICATION_SEND_URL = "https://util.devi.tools/api/v1/notify"

[development]
    APP_NAME = "meios de pagamento"
    DATABASE_URL = "sqlite:///database_development.db"
    TRANSFER_AUTHORIZATION_URL = "https://util.devi.tools/api/v2/authorize"
    TRANSFER_NOTIFICATION_SEND_URL = "https://util.devi.tools/api/v1/notify"

[production]
    APP_NAME = "meios de pagamento"
    DATABASE_URL = "sqlite:///database_production.db"
    TRANSFER_AUTHORIZATION_URL = "https://util.devi.tools/api/v2/authorize"
    TRANSFER_NOTIFICATION_SEND_URL = "https://util.devi.tools/api/v1/notify"
    